name: Node.js CI

on:
  push:
    branches: [ main ]
    pull_request:
        branches: [ main ]
    
    
jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        yarn install
        yarn workspace server install
        yarn start
        pm2 stop 0
        pm2 start 0
        pm2 save
        sudo
        sudo service apache2 stop
        sudo service nginx restart
